steps:

  # Run the linters and unit tests
  - name: python:3.10-slim
    id: Lint-Test
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install poetry && \
        poetry export -f requirements.txt --output requirements.txt --without-hashes --with=dev && \
        pip install --no-cache-dir -r requirements.txt && \
        black app/ tests/ && \
        flake8 app/ tests/ && \
        mypy app/ tests/ && \
        pytest

  # Build the container image
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
    - build
    - -t
    - us-central1-docker.pkg.dev/$PROJECT_ID/gcp-img-rep/ct-api:$COMMIT_SHA
    - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/gcp-img-rep/ct-api:$COMMIT_SHA